import { AssessmentEngine } from './src/lib/assessment-engine';

const sampleScores = {
    "team_size": 120, "team_experience": 22, "ceo_background": 9.5, "cto_background": 8.5, "cmo_background": 9.0, "cfo_background": 9.2, "team_stability": 9.0, "team_complementarity": 8.5, "advisor_quality": 8.0, "board_quality": 9.0, "team_education": 8.5, "team_network": 9.2, "team_culture": 8.5, "team_innovation": 8.0, "team_execution": 9.0,
    "product_maturity": 9.5, "tech_innovation": 8.5, "tech_barriers": 9.0, "ip_portfolio": 352, "product_demand": 9.2, "user_experience": 8.2, "product_quality": 9.5, "development_speed": 7.5, "rd_budget": 8.5, "rd_team_size": 850, "product_roadmap": 8.8, "tech_scalability": 9.0, "data_assets": 8.5, "algorithm_advantage": 8.0, "platform_ecosystem": 7.5, "product_differentiation": 8.8, "integration_capability": 8.5, "tech_trend_alignment": 8.5, "product_patent": 9.0, "quality_certification": 10,
    "market_size": 5000, "market_growth": 12, "market_share": 12.5, "customer_acquisition": 150, "customer_retention": 95, "brand_awareness": 9.2, "sales_growth": 15, "channel_coverage": 9.5, "competition_intensity": 8.0, "competitive_advantage": 9.0, "overseas_expansion": 8.5, "customer_satisfaction": 9.2, "customer_lifetime_value": 850000, "market_position": 9.5, "pricing_power": 8.8, "distribution_network": 9.2, "marketing_efficiency": 8.5, "market_penetration": 25, "competitor_count": 12, "barrier_to_entry": 9.5,
    "revenue": 1250000, "revenue_growth": 18, "gross_margin": 25, "net_margin": 12, "burn_rate": 1500, "cash_runway": 36, "asset_liability_ratio": 45, "current_ratio": 1.5, "roi": 18, "roe": 15, "customer_acquisition_cost": 8, "revenue_per_employee": 250, "profit_per_employee": 30, "funding_history": 9.5, "investor_quality": 9.5, "valuation_multiple": 8.5, "financial_control": 9.5, "audit_quality": 9.8,
    "operational_efficiency": 180, "process_standardization": 9.2, "supply_chain": 9.5, "production_capacity": 88, "quality_control": 9.5, "employee_productivity": 6500, "it_infrastructure": 8.8, "operational_risk": 9.2, "cost_control": 8.5, "asset_utilization": 82, "vendor_management": 9.0, "logistics_capability": 12, "scalability": 8.5, "crisis_management": 9.2, "compliance": 9.8,
    "strategy_clarity": 9.5, "business_model": 9.2, "corporate_governance": 9.5, "risk_management": 9.2, "succession_plan": 8.5, "csr": 9.0, "esg_score": 8.8, "innovation_culture": 8.5, "strategic_partnerships": 9.2, "long_term_vision": 9.5, "sustainable_growth": 15, "market_expansion": 8.8, "product_pipeline": 15, "talent_attraction": 9.2, "climate_impact": 9.0, "resource_efficiency": 8.5, "community_engagement": 8.2, "adaptability": 8.8, "reputation_management": 9.2, "future_readiness": 9.5
};

const result = AssessmentEngine.runFullAssessment(sampleScores);
console.log(JSON.stringify(result.categoryScores, null, 2));
